package com.tunara.api.service;
import com.tunara.api.client.TunaraAiClient; import com.tunara.api.dto.*; import com.tunara.api.entity.*; import com.tunara.api.event.SongGenerationRequestedEvent; import com.tunara.api.repository.*; import org.springframework.scheduling.annotation.Async; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.*; import org.springframework.transaction.event.*; import java.time.OffsetDateTime;
@Service public class SongGenerationDispatcher {
 private final TunaraAiClient ai; private final SongRepository songs; private final GenerationJobRepository jobs;
 public SongGenerationDispatcher(TunaraAiClient a,SongRepository s,GenerationJobRepository j){ai=a;songs=s;jobs=j;}
 @Async @TransactionalEventListener(phase=TransactionPhase.AFTER_COMMIT) public void dispatch(SongGenerationRequestedEvent e){processing(e);try{complete(e,ai.generateSong(new AiGenerateSongRequest(e.songId(),e.prompt(),e.genre(),e.voice(),e.language(),e.durationSeconds())));}catch(Exception x){fail(e,x);}}
 @Transactional(propagation=Propagation.REQUIRES_NEW) public void processing(SongGenerationRequestedEvent e){Song s=songs.findById(e.songId()).orElseThrow();GenerationJob j=jobs.findById(e.generationJobId()).orElseThrow();s.setStatus(SongStatus.PROCESSING);j.setStatus(GenerationJobStatus.PROCESSING);j.setProgress(10);j.setStartedAt(OffsetDateTime.now());j.setErrorMessage(null);songs.save(s);jobs.save(j);}
 @Transactional(propagation=Propagation.REQUIRES_NEW) public void complete(SongGenerationRequestedEvent e,AiGenerateSongResponse r){if(r==null||blank(r.title())||blank(r.lyrics())||blank(r.wavUrl())||blank(r.midiUrl())||blank(r.logicPackUrl()))throw new IllegalStateException("Tunara AI returned an incomplete Logic pack response");Song s=songs.findById(e.songId()).orElseThrow();GenerationJob j=jobs.findById(e.generationJobId()).orElseThrow();s.setTitle(r.title().trim());s.setLyrics(r.lyrics().trim());s.setWavUrl(r.wavUrl().trim());s.setMidiUrl(r.midiUrl().trim());s.setLogicPackUrl(r.logicPackUrl().trim());s.setStatus(SongStatus.COMPLETED);j.setStatus(GenerationJobStatus.COMPLETED);j.setProgress(100);j.setCompletedAt(OffsetDateTime.now());j.setErrorMessage(null);songs.save(s);jobs.save(j);}
 @Transactional(propagation=Propagation.REQUIRES_NEW) public void fail(SongGenerationRequestedEvent e,Exception x){Song s=songs.findById(e.songId()).orElseThrow();GenerationJob j=jobs.findById(e.generationJobId()).orElseThrow();s.setStatus(SongStatus.FAILED);j.setStatus(GenerationJobStatus.FAILED);String m=x.getMessage();j.setErrorMessage(m==null?"Generation failed":m.substring(0,Math.min(m.length(),1000)));j.setCompletedAt(OffsetDateTime.now());songs.save(s);jobs.save(j);}
 private boolean blank(String s){return s==null||s.isBlank();}
}
