import copy
import os
import re
from pathlib import Path
from typing import Any

import pretty_midi
import yaml


class OpenUtauProjectService:
    SECTION_PATTERN = re.compile(r"^\s*\[[^]]+]\s*$")
    WORD_PATTERN = re.compile(r"[A-Za-zÁÉÍÓÚÜÑáéíóúüñ']+")
    VOWEL_GROUP_PATTERN = re.compile(
        r"[aeiouáéíóúü]+",
        re.IGNORECASE,
    )
    SPANISH_PHONEMIZER = (
        "OpenUtau.Core.DiffSinger.DiffSingerSpanishPhonemizer"
    )

    def __init__(self) -> None:
        self.public_base_url = os.getenv(
            "AUDIO_PUBLIC_BASE_URL",
            "http://localhost:8001",
        ).rstrip("/")
        self.midi_directory = Path(
            os.getenv("MIDI_OUTPUT_DIRECTORY", "generated-midi")
        ).resolve()
        self.output_directory = Path(
            os.getenv("OPENUTAU_OUTPUT_DIRECTORY", "generated-openutau")
        ).resolve()
        self.template_path = Path(
            os.getenv(
                "OPENUTAU_TEMPLATE_PATH",
                "resources/Tunara-Vocal-Template.ustx",
            )
        ).resolve()
        self.output_directory.mkdir(parents=True, exist_ok=True)

    async def generate(
        self,
        song_id: str,
        title: str,
        lyrics: str,
        bpm: int,
    ) -> str:
        safe_song_id = self._safe_song_id(song_id)
        midi_path = self.midi_directory / f"{safe_song_id}-vocal.mid"

        if not self.template_path.exists():
            raise RuntimeError(
                f"OpenUtau template not found: {self.template_path}"
            )

        if not midi_path.exists():
            raise RuntimeError(
                f"Vocal melody MIDI not found: {midi_path}"
            )

        project = copy.deepcopy(
            yaml.safe_load(self.template_path.read_text(encoding="utf-8"))
        )
        midi = pretty_midi.PrettyMIDI(str(midi_path))
        notes = self._vocal_notes(midi)
        lyric_tokens = self._openutau_lyric_tokens(lyrics)

        if not notes:
            raise RuntimeError("The vocal MIDI contains no notes")

        if not lyric_tokens:
            raise RuntimeError("The lyrics contain no singable words")

        project["name"] = title
        project["comment"] = "Generated by Tunara for AI2 v102"
        project["bpm"] = float(bpm)
        project["tempos"] = [{"position": 0, "bpm": float(bpm)}]
        project["tracks"] = [self._vocal_track(project)]

        ustx_notes = []
        ustx_ticks_per_beat = 480
        midi_to_ustx_scale = ustx_ticks_per_beat / midi.resolution
        usable_note_count = min(len(notes), len(lyric_tokens))

        for index, note in enumerate(notes[:usable_note_count]):
            lyric = lyric_tokens[index]
            midi_position = midi.time_to_tick(note.start)
            midi_end_position = midi.time_to_tick(note.end)
            position = int(round(midi_position * midi_to_ustx_scale))
            end_position = int(round(midi_end_position * midi_to_ustx_scale))
            duration = max(120, end_position - position)

            ustx_notes.append(
                {
                    "position": position,
                    "duration": duration,
                    "tone": int(note.pitch),
                    "lyric": lyric,
                    "pitch": {
                        "data": [
                            {"x": -40, "y": 0, "shape": "io"},
                            {"x": 40, "y": 0, "shape": "io"},
                        ],
                        "snap_first": True,
                    },
                    "vibrato": {
                        "length": 35 if duration >= ustx_ticks_per_beat else 0,
                        "period": 175,
                        "depth": 25,
                        "in": 10,
                        "out": 10,
                        "shift": 0,
                        "drift": 0,
                        "vol_link": 0,
                    },
                    "tuning": 0,
                    "phoneme_expressions": [],
                    "phoneme_overrides": [],
                }
            )

        total_duration = max(
            note["position"] + note["duration"]
            for note in ustx_notes
        )

        project["voice_parts"] = [
            {
                "duration": total_duration,
                "name": title,
                "comment": (
                    "Spanish lyrics use complete words followed by + extension notes"
                ),
                "track_no": 0,
                "position": 0,
                "notes": ustx_notes,
                "curves": [
                    {"xs": [], "ys": [], "abbr": "tenc"},
                    {"xs": [], "ys": [], "abbr": "dyn"},
                ],
            }
        ]
        project["wave_parts"] = []

        output_path = self.output_directory / f"{safe_song_id}-vocals.ustx"
        output_path.write_text(
            yaml.safe_dump(
                project,
                allow_unicode=True,
                sort_keys=False,
                width=120,
            ),
            encoding="utf-8",
        )

        return f"{self.public_base_url}/openutau/{output_path.name}"

    def _vocal_track(self, project: dict[str, Any]) -> dict[str, Any]:
        for track in project.get("tracks", []):
            if track.get("renderer_settings", {}).get("renderer") == "DIFFSINGER":
                selected = copy.deepcopy(track)
                selected["track_name"] = "Tunara Vocals"
                selected["phonemizer"] = self.SPANISH_PHONEMIZER
                selected["mute"] = False
                selected["solo"] = False
                return selected

        raise RuntimeError(
            "The template does not contain a configured DiffSinger track"
        )

    def _vocal_notes(self, midi: pretty_midi.PrettyMIDI):
        for instrument in midi.instruments:
            if not instrument.is_drum and instrument.notes:
                return sorted(instrument.notes, key=lambda note: note.start)
        return []

    def _openutau_lyric_tokens(self, lyrics: str) -> list[str]:
        tokens: list[str] = []

        for line in lyrics.splitlines():
            cleaned = line.strip()
            if not cleaned or self.SECTION_PATTERN.match(cleaned):
                continue

            for word in self.WORD_PATTERN.findall(cleaned):
                normalized_word = word.lower()
                syllable_count = self._estimated_syllable_count(normalized_word)
                tokens.append(normalized_word)
                tokens.extend("+" for _ in range(max(0, syllable_count - 1)))

        return tokens

    def _estimated_syllable_count(self, word: str) -> int:
        groups = self.VOWEL_GROUP_PATTERN.findall(word)
        return max(1, len(groups))

    def _safe_song_id(self, song_id: str) -> str:
        return "".join(
            character
            for character in song_id
            if character.isalnum() or character in {"-", "_"}
        )
